version: "3"

services:
    notification-service:
        build: .
        ports:
            - "8085:8085"
        environment:
            - PORT=8085
            - MONGODB_URI=mongodb://mongo:27017/notificationdb
            - RABBITMQ_URL=amqp://rabbitmq:5672
            - EMAIL_SERVICE=smtp
            - EMAIL_HOST=smtp.ethereal.email
            - EMAIL_PORT=587
            - EMAIL_USER=marlin.dooley87@ethereal.email
            - EMAIL_PASS=BKgQuJy4ts7ExCBXM6
            - EMAIL_FROM=noreply@ecommerce.com
        depends_on:
            - mongo
            - rabbitmq
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - app-network

    mongo:
        image: mongo:latest
        ports:
            - "27020:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongo-data:
