apiVersion: v1
kind: ConfigMap
metadata:
    name: notification-service-config
    namespace: ecommerce
    labels:
        app: notification-service
        component: config
    annotations:
        description: "Configuration for Notification Service"
        version: "1.0"
data:
    # Service Configuration
    PORT: "8085"
    NODE_ENV: "production"

    # MongoDB Configuration
    MONGODB_URI: "mongodb://mongo:27017/notificationdb"

    # RabbitMQ Configuration
    RABBITMQ_URL: "amqp://rabbitmq:5672"

    # Service URLs
    USER_SERVICE_URL: "http://user-service:8081"
    ORDER_SERVICE_URL: "http://order-service:8083"

    # Email Configuration
    EMAIL_SERVICE: "smtp"
    EMAIL_HOST: "smtp.mailtrap.io"
    EMAIL_PORT: "2525"
    EMAIL_FROM: "noreply@ecommerce.com"
