apiVersion: v1
kind: Secret
metadata:
    name: notification-service-secrets
    namespace: ecommerce
    labels:
        app: notification-service
        component: secrets
    annotations:
        description: "Sensitive configuration for Notification Service"
        version: "1.0"
type: Opaque
# Note: Values must be base64 encoded
# To encode: echo -n "your-value" | base64
data:
    # Email credentials
    EMAIL_USER: bWFybGluLmRvb2xleTg3QGV0aGVyZWFsLmVtYWls
    EMAIL_PASS: QktnUXVKeTR0czdFeENCWE02
    EMAIL_HOST: c210cC5ldGhlcmVhbC5lbWFpbA==
    EMAIL_PORT: NTg3
    EMAIL_FROM: bm9yZXBseUBlY29tbWVyY2UuY29t

    # JWT and Service secrets
    JWT_SECRET: YmZmNTliNGI2NjYxM2NiMjkzODUzNDY1MzE0ZDAxNTQ5ZWRjZTQ5N2Q4YzYxMmE0YzhiNzM3MDA4MmYzODI4MjgyZWQ5ZGUwZjE3ZmM0ZmNlMTI0Y2MxNDJiMjEyZWFjYzczN2Y0NjU0OWJjNjI5NTgxNGM4ZDEwMzRlYmIzOWRiNzVjMzA2NDY1ZjdjMzRhZmI5ZjJjYjM0MDY3ZmE4ZWIyNjc0YWQ5YjRhZjI5ZmU5ZjJmZTYwZDM5YmQ3YzMzYmRlMzI5NTFkM2Y5Y2IxYTUxNWNhZTUzYzZiYTA3OTgzZDEwYzI3MjlhOTM5MDdiNTc4ODAyMTFiN2M1YzkxN2QxMzllMDE5NmJlYzQyY2E3MjcxNWQ1Y2RmMjEyMTlkZGJjNWM2NWI3MzA4Mjk2NGI3NDcyOWRiZGJiMjRjMGNmMjgyNzk2MDJiYzJkOTBkMDZlYjhmNGM4ZjZkNzJhMTc4YjRkZjE3YWIyZmM3MDhmZDRiY2MxMGRmYTNkZjk0MGFlN2JlYTlmOWVhZDk2NTJmMzJjODg5NjZjOGIyOTJlMmU2NmEzYzk0NWFiZDI3MjFlMzNiY2Q2MzljNjZhNWE5MWQ0NGQ2ZWIyZjBlNjE1NjJlZDg1ZDkyOGJlYzU5Y2NkZTAwZDYxMDlhMTgzOTFiODc1OTE3YmFhNjFmNQ==
    SERVICE_SECRET: ZjUwM2Q4OTM5ZGMwMmUwOTc2ZGRhYjc2MGZhYTFmNTdhMWQyMzkwNzcyZjcwZGRiYjZkY2M4NThlOTYzOTlmNTE4N2ZmNWFhOWNhMjRhYWVkOGU2ZTZjMzNlMWM3ZTdjZDA4ZjIzYTA3ODNhMThmZDBkM2VkYjRkNjNiYTZmZDg5OGExMDA5MTU3MWQzNzdhYjQ5OGIyNzU4ODAyNzJjMWNiYjJmNWYwNjMyNzgxZTUxY2ZkNjg3ZDkyYjZmZThhYzNjZTNjNzQ3MmI5MzcxMjdkNTYzNmIxZTM5NGQxYWRiMWVkYTlhNGY5NDYzNDBlZWI4NmExMDk4YTlhYmNhMmE0NDc0YjhmZjQ1NjVlNTkxNDVlZmRmMTE4NWYxYzljNzgxMTNhNmUwOTMyMmUyMmY3ZTc0YjY3MWU5OTVkZWRlNjU2NDI5ZmQ3NDkxNmIyNGJkMWZiNGNhMjllMjllZTYxZTExYmYyZDk3ZDcyYTFhYmRjZGI0ZTZmNzYxMjQzMDVhOTYyZTYwMTRmNzhlOGFiNGRiMTM3NjU2OGQ5NTUwNDk0NGRkM2NhZTUzOGU1OGNhMzFjY2RmOTIzOGYwNzQ0NTA3MGYyNjQzZGE2YThhMjE5MGQ0YzUxZmE5NjVlMjVkYjk4NDc0NzcyYzllNDI0YTY2OTY4MDJiYzk3M2Q=
